/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WordCardImport } from './routes/word-card'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WordCardRoute = WordCardImport.update({
  id: '/word-card',
  path: '/word-card',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/word-card': {
      id: '/word-card'
      path: '/word-card'
      fullPath: '/word-card'
      preLoaderRoute: typeof WordCardImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/word-card': typeof WordCardRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/word-card': typeof WordCardRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/word-card': typeof WordCardRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/word-card'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/word-card'
  id: '__root__' | '/' | '/word-card'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WordCardRoute: typeof WordCardRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WordCardRoute: WordCardRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/word-card"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/word-card": {
      "filePath": "word-card.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
