/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WordCardImport } from './routes/word-card'
import { Route as SettingsPageImport } from './routes/settings-page'
import { Route as IndexImport } from './routes/index'
import { Route as SettingsDefaultPropertiesImport } from './routes/settings/default-properties'
import { Route as SettingsChangePropertiesImport } from './routes/settings/change-properties'

// Create/Update Routes

const WordCardRoute = WordCardImport.update({
  id: '/word-card',
  path: '/word-card',
  getParentRoute: () => rootRoute,
} as any)

const SettingsPageRoute = SettingsPageImport.update({
  id: '/settings-page',
  path: '/settings-page',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsDefaultPropertiesRoute = SettingsDefaultPropertiesImport.update({
  id: '/settings/default-properties',
  path: '/settings/default-properties',
  getParentRoute: () => rootRoute,
} as any)

const SettingsChangePropertiesRoute = SettingsChangePropertiesImport.update({
  id: '/settings/change-properties',
  path: '/settings/change-properties',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/settings-page': {
      id: '/settings-page'
      path: '/settings-page'
      fullPath: '/settings-page'
      preLoaderRoute: typeof SettingsPageImport
      parentRoute: typeof rootRoute
    }
    '/word-card': {
      id: '/word-card'
      path: '/word-card'
      fullPath: '/word-card'
      preLoaderRoute: typeof WordCardImport
      parentRoute: typeof rootRoute
    }
    '/settings/change-properties': {
      id: '/settings/change-properties'
      path: '/settings/change-properties'
      fullPath: '/settings/change-properties'
      preLoaderRoute: typeof SettingsChangePropertiesImport
      parentRoute: typeof rootRoute
    }
    '/settings/default-properties': {
      id: '/settings/default-properties'
      path: '/settings/default-properties'
      fullPath: '/settings/default-properties'
      preLoaderRoute: typeof SettingsDefaultPropertiesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings-page': typeof SettingsPageRoute
  '/word-card': typeof WordCardRoute
  '/settings/change-properties': typeof SettingsChangePropertiesRoute
  '/settings/default-properties': typeof SettingsDefaultPropertiesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings-page': typeof SettingsPageRoute
  '/word-card': typeof WordCardRoute
  '/settings/change-properties': typeof SettingsChangePropertiesRoute
  '/settings/default-properties': typeof SettingsDefaultPropertiesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/settings-page': typeof SettingsPageRoute
  '/word-card': typeof WordCardRoute
  '/settings/change-properties': typeof SettingsChangePropertiesRoute
  '/settings/default-properties': typeof SettingsDefaultPropertiesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings-page'
    | '/word-card'
    | '/settings/change-properties'
    | '/settings/default-properties'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings-page'
    | '/word-card'
    | '/settings/change-properties'
    | '/settings/default-properties'
  id:
    | '__root__'
    | '/'
    | '/settings-page'
    | '/word-card'
    | '/settings/change-properties'
    | '/settings/default-properties'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsPageRoute: typeof SettingsPageRoute
  WordCardRoute: typeof WordCardRoute
  SettingsChangePropertiesRoute: typeof SettingsChangePropertiesRoute
  SettingsDefaultPropertiesRoute: typeof SettingsDefaultPropertiesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsPageRoute: SettingsPageRoute,
  WordCardRoute: WordCardRoute,
  SettingsChangePropertiesRoute: SettingsChangePropertiesRoute,
  SettingsDefaultPropertiesRoute: SettingsDefaultPropertiesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/settings-page",
        "/word-card",
        "/settings/change-properties",
        "/settings/default-properties"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/settings-page": {
      "filePath": "settings-page.tsx"
    },
    "/word-card": {
      "filePath": "word-card.tsx"
    },
    "/settings/change-properties": {
      "filePath": "settings/change-properties.tsx"
    },
    "/settings/default-properties": {
      "filePath": "settings/default-properties.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
